# Generated by Django 2.2.3 on 2019-07-26 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='UserProfile.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rec_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
